apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: aksdemo
  labels:
    app: aksdemo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aksdemo
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown: 
      stabilizationWindowSeconds: 300 # Estabilização para scale down em segundos
    scaleUp:
      stabilizationWindowSeconds: 180 # Estabilização para scale up em segundos
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
