apiVersion: v1
kind: Service
metadata:
  labels:
    app: aksdemo
  name: aksdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aksdemo
status:
  loadBalancer: {}
